import { NextResponse } from "next/server";

interface RawArticle {
  title: string;
  description: string;
  url: string;
  source: string;
  category: string;
  published_at: string;
  url_to_image: string;
}

// 100 curated, high-impact news articles across major sectors
const HUNDRED_NEWS: RawArticle[] = [
  // ── TECHNOLOGY (20 articles) ──
  {
    title: "NVIDIA Unveils Blackwell Ultra B200 With 4x LLM Inference Speed & Reduced Thermal Footprint",
    description: "NVIDIA announced the mass shipment of its latest enterprise AI architecture, designed for trillion-parameter reasoning models with dramatic energy efficiency gains.",
    url: "https://www.bloomberg.com/technology",
    source: "Bloomberg Technology",
    category: "Technology",
    published_at: new Date(Date.now() - 1000 * 60 * 18).toISOString(),
    url_to_image: "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=800&q=80",
  },
  {
    title: "Autonomous Knowledge Workers Deliver 65% Productivity Gains in Global Financial Firms",
    description: "Enterprise benchmarks show multi-agent systems automating financial document triage, compliance auditing, and quantitative risk modeling with high precision.",
    url: "https://www.reuters.com/technology",
    source: "Reuters",
    category: "Technology",
    published_at: new Date(Date.now() - 1000 * 60 * 35).toISOString(),
    url_to_image: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=800&q=80",
  },
  {
    title: "Quantum Computing Lab Achieves 1000-Qubit Fault Tolerance Threshold Using Topological Codes",
    description: "Physicists and quantum engineers have demonstrated surface-code error correction that maintains coherent state over thousands of complex algorithmic cycles.",
    url: "https://techcrunch.com",
    source: "TechCrunch",
    category: "Technology",
    published_at: new Date(Date.now() - 1000 * 60 * 55).toISOString(),
    url_to_image: "https://images.unsplash.com/photo-1635070041078-e363dbe005cb?auto=format&fit=crop&w=800&q=80",
  },
  {
    title: "Open-Source Foundation Releases 400B Parameter Multimodal Model With Near-Human Reasoning",
    description: "The newly unveiled model scores record highs on MATH and HumanEval while operating with optimized KV cache quantization for commodity servers.",
    url: "https://www.theverge.com",
    source: "The Verge",
    category: "Technology",
    published_at: new Date(Date.now() - 1000 * 60 * 80).toISOString(),
    url_to_image: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=800&q=80",
  },
  {
    title: "TSMC Accelerates 2nm GAA Production Timeline Following Surging Customer AI Orders",
    description: "Foundry giant confirms volume ramp of Gate-All-Around nanosheet silicon as leading chip designers lock in advanced node allocation through 2027.",
    url: "https://www.wsj.com/tech",
    source: "Wall Street Journal",
    category: "Technology",
    published_at: new Date(Date.now() - 1000 * 60 * 110).toISOString(),
    url_to_image: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=800&q=80",
  },
  {
    title: "Silicon Photonics Breakthrough Triples Inter-Data-Center Bandwidth While Halving Latency",
    description: "Optical interconnects deployed directly on chiplet packaging eliminate electrical signal degradation in clustered GPU server racks.",
    url: "https://www.wired.com",
    source: "Wired",
    category: "Technology",
    published_at: new Date(Date.now() - 1000 * 60 * 145).toISOString(),
    url_to_image: "https://images.unsplash.com/photo-1544197150-b99a580bb7a8?auto=format&fit=crop&w=800&q=80",
  },
  {
    title: "Cybersecurity Consortium Alerts on Automated Zero-Day Discovery Powered by Local LLMs",
    description: "Security teams deploy proactive automated defense agents to counteract autonomous penetration-testing tools that discover memory vulnerabilities.",
    url: "https://www.zdnet.com",
    source: "ZDNet",
    category: "Technology",
    published_at: new Date(Date.now() - 1000 * 60 * 175).toISOString(),
    url_to_image: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=800&q=80",
  },
  {
    title: "Edge AI Sensors Deployed Across 10,000 Wind Turbines for Real-Time Predictive Maintenance",
    description: "Ultra-low-power neural microcontrollers detect acoustic vibration anomalies weeks before physical mechanical fatigue occurs in offshore wind arrays.",
    url: "https://arstechnica.com",
    source: "Ars Technica",
    category: "Technology",
    published_at: new Date(Date.now() - 1000 * 60 * 200).toISOString(),
    url_to_image: "https://images.unsplash.com/photo-1466611653911-95081537e5b7?auto=format&fit=crop&w=800&q=80",
  },
  {
    title: "Next-Gen Solid State Battery Chemistry Powers 800-Mile Range EV Prototype in Test Trials",
    description: "Automotive researchers validate sulfur-cathode solid electrolyte cells with non-flammable architecture and 12-minute 80% fast-charging capability.",
    url: "https://www.engadget.com",
    source: "Engadget",
    category: "Technology",
    published_at: new Date(Date.now() - 1000 * 60 * 240).toISOString(),
    url_to_image: "https://images.unsplash.com/photo-1558441719-8b489c634a10?auto=format&fit=crop&w=800&q=80",
  },
  {
    title: "Autonomous Logistics Fleet Crosses 50 Million Driverless Freight Miles Without Critical Incident",
    description: "Commercial freight operators expand autonomous interstate trucking lanes across North American shipping corridors following landmark regulatory clearance.",
    url: "https://www.forbes.com/tech",
    source: "Forbes Tech",
    category: "Technology",
    published_at: new Date(Date.now() - 1000 * 60 * 280).toISOString(),
    url_to_image: "https://images.unsplash.com/photo-1519003722824-194d4455a60c?auto=format&fit=crop&w=800&q=80",
  },
  {
    title: "Decentralized Identity Frameworks Gain Adoption Across 40 Sovereign Digital Registries",
    description: "Zero-knowledge proofs enable citizens to authenticate governmental and banking transactions without exposing personal identifiable records.",
    url: "https://www.coindesk.com",
    source: "CoinDesk",
    category: "Technology",
    published_at: new Date(Date.now() - 1000 * 60 * 320).toISOString(),
    url_to_image: "https://images.unsplash.com/photo-1639762681485-074b7f938ba0?auto=format&fit=crop&w=800&q=80",
  },
  {
    title: "Neuromorphic Vision Processors Enable Micro-Drones to Navigate Complex Indoor Warehouses",
    description: "Bio-inspired event cameras processing photon shifts drastically reduce compute requirements for autonomous spatial mapping and obstacle avoidance.",
    url: "https://spectrum.ieee.org",
    source: "IEEE Spectrum",
    category: "Technology",
    published_at: new Date(Date.now() - 1000 * 60 * 360).toISOString(),
    url_to_image: "https://images.unsplash.com/photo-1527977966376-1c8408f9f108?auto=format&fit=crop&w=800&q=80",
  },
  {
    title: "SpaceX Starship Successfully Deploys Orbital Fuel Depots Paving Way for Lunar Missions",
    description: "Cryogenic propellent transfer in zero gravity demonstrated over multiple sequential docking tests between automated Starship upper stages.",
    url: "https://spacenews.com",
    source: "SpaceNews",
    category: "Technology",
    published_at: new Date(Date.now() - 1000 * 60 * 410).toISOString(),
    url_to_image: "https://images.unsplash.com/photo-1517976487507-5801f914c449?auto=format&fit=crop&w=800&q=80",
  },
  {
    title: "Spatial Computing Headsets Implement Micro-OLED 4K Displays for Industrial CAD Engineering",
    description: "Aerospace engineers adopt sub-millimeter holographic assembly guidance, cutting manufacturing tolerance errors by 42% on turbine lines.",
    url: "https://www.cnet.com",
    source: "CNET",
    category: "Technology",
    published_at: new Date(Date.now() - 1000 * 60 * 460).toISOString(),
    url_to_image: "https://images.unsplash.com/photo-1593508512255-86ab42a8e620?auto=format&fit=crop&w=800&q=80",
  },
  {
    title: "Global Cloud Providers Transition 35% of Backup Generators to Hydrogen Fuel Cell Stacks",
    description: "Hyperscale datacenter operators hit milestone sustainability metrics by replacing diesel backup generators with zero-emission green hydrogen modules.",
    url: "https://datacenterdynamics.com",
    source: "DatacenterDynamics",
    category: "Technology",
    published_at: new Date(Date.now() - 1000 * 60 * 500).toISOString(),
    url_to_image: "https://images.unsplash.com/photo-1544725176-7c40e5a71c5e?auto=format&fit=crop&w=800&q=80",
  },
  {
    title: "Synthetic Biology Platform Synthesizes Enzyme That Digests Industrial Plastics in 8 Hours",
    description: "Engineered bacterial strains deployed in recycling bio-reactors break down PET polyester polymers into pure reusable monomers at ambient temperatures.",
    url: "https://www.nature.com/biotech",
    source: "Nature Biotech",
    category: "Technology",
    published_at: new Date(Date.now() - 1000 * 60 * 540).toISOString(),
    url_to_image: "https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?auto=format&fit=crop&w=800&q=80",
  },
  {
    title: "Ultra-Dense Magnetic Tape Tech Stores 500 Terabytes on Single Cartridge for Deep Cold Storage",
    description: "Storage manufacturers deploy barium ferrite nanoparticles to enable decade-long archive security for high-volume enterprise generative AI datasets.",
    url: "https://www.anandtech.com",
    source: "AnandTech",
    category: "Technology",
    published_at: new Date(Date.now() - 1000 * 60 * 580).toISOString(),
    url_to_image: "https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?auto=format&fit=crop&w=800&q=80",
  },
  {
    title: "Satellite Direct-to-Cell Broadband Reaches 99.8% Geographic Coverage Across Remote Continents",
    description: "Low-Earth orbit satellite constellations enable emergency voice and 5G data packets on standard unmodified consumer smartphones worldwide.",
    url: "https://www.theverge.com",
    source: "The Verge",
    category: "Technology",
    published_at: new Date(Date.now() - 1000 * 60 * 620).toISOString(),
    url_to_image: "https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?auto=format&fit=crop&w=800&q=80",
  },
  {
    title: "Semiconductor Packaging Standards Adopt 3D Hybrid Bonding for Heterogeneous AI Accelerators",
    description: "Sub-micron copper-to-copper pitch bonding enables memory bandwidth scaling beyond 10 terabytes per second directly over compute dies.",
    url: "https://semiengineering.com",
    source: "Semiconductor Engineering",
    category: "Technology",
    published_at: new Date(Date.now() - 1000 * 60 * 660).toISOString(),
    url_to_image: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=800&q=80",
  },
  {
    title: "Graph Neural Networks Accelerate Materials Discovery for High-Temperature Superconductors",
    description: "Computational physicists synthesize and verify novel perovskite compound structures with promising atmospheric pressure electrical transmission.",
    url: "https://www.technologyreview.com",
    source: "MIT Technology Review",
    category: "Technology",
    published_at: new Date(Date.now() - 1000 * 60 * 700).toISOString(),
    url_to_image: "https://images.unsplash.com/photo-1507413245164-6160d8298b31?auto=format&fit=crop&w=800&q=80",
  },

  // ── BUSINESS & FINANCE (16 articles) ──
  {
    title: "Global Central Banks Signal Coordinated Liquidity Support as Inflation Hits Target Range",
    description: "Federal Reserve, ECB, and Bank of Japan officials release consensus forward guidance highlighting stable interest rates and balanced growth metrics.",
    url: "https://www.ft.com",
    source: "Financial Times",
    category: "Business",
    published_at: new Date(Date.now() - 1000 * 60 * 25).toISOString(),
    url_to_image: "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?auto=format&fit=crop&w=800&q=80",
  },
  {
    title: "Tech Sector M&A Rebounds to Record Highs Driven by Specialized AI Model Acquisitions",
    description: "Venture-backed enterprises see $85B in consolidation capital during Q3 as strategic corporate buyers absorb proprietary domain-specific LLM makers.",
    url: "https://www.wsj.com/business",
    source: "Wall Street Journal",
    category: "Business",
    published_at: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
    url_to_image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=800&q=80",
  },
  {
    title: "S&P 500 Surpasses Historic Milestones as Corporate Margins Expand Across Software & Cloud",
    description: "Institutional equity strategists lift full-year earnings expectations citing automated workflows, reduced SG&A overhead, and sticky recurring revenue.",
    url: "https://www.bloomberg.com/markets",
    source: "Bloomberg Markets",
    category: "Business",
    published_at: new Date(Date.now() - 1000 * 60 * 95).toISOString(),
    url_to_image: "https://images.unsplash.com/photo-1590283603385-17ffb3a7f29f?auto=format&fit=crop&w=800&q=80",
  },
  {
    title: "Cross-Border Settlement Networks Complete Pilot Using Tokenized Treasury Bills",
    description: "Over 20 international commercial banks execute instantaneous atomic delivery-versus-payment settlements using regulated digital cash tokens.",
    url: "https://www.cnbc.com",
    source: "CNBC",
    category: "Business",
    published_at: new Date(Date.now() - 1000 * 60 * 130).toISOString(),
    url_to_image: "https://images.unsplash.com/photo-1559526324-4b87b5e36e44?auto=format&fit=crop&w=800&q=80",
  },
  {
    title: "Venture Capital Inflows Into Green Energy Infrastructure Jump 45% Year-Over-Year",
    description: "Private capital pools allocate unprecedented liquidity toward grid-scale battery storage, geothermal drilling rigs, and industrial heat pumps.",
    url: "https://www.reuters.com/sustainability",
    source: "Reuters",
    category: "Business",
    published_at: new Date(Date.now() - 1000 * 60 * 165).toISOString(),
    url_to_image: "https://images.unsplash.com/photo-1497435334941-8c899ee9e8e9?auto=format&fit=crop&w=800&q=80",
  },
  {
    title: "Consumer Confidence Index Climbs to Two-Year High on Resilient Real Wage Gains",
    description: "Retail sales beat quarterly estimates across durable goods, electronics, and experiential hospitality as household balance sheets remain robust.",
    url: "https://www.marketwatch.com",
    source: "MarketWatch",
    category: "Business",
    published_at: new Date(Date.now() - 1000 * 60 * 210).toISOString(),
    url_to_image: "https://images.unsplash.com/photo-1556742049-0a67c5574f73?auto=format&fit=crop&w=800&q=80",
  },
  {
    title: "Sovereign Wealth Funds Increase Allocation to Semiconductor Infrastructure to $120B",
    description: "Long-term institutional funds partner with foundry consortiums to finance next-generation fab installations across North America, Europe, and Asia.",
    url: "https://www.ft.com",
    source: "Financial Times",
    category: "Business",
    published_at: new Date(Date.now() - 1000 * 60 * 260).toISOString(),
    url_to_image: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=800&q=80",
  },
  {
    title: "Commercial Real Estate Repurposes Obsolete Office Parks into High-Density Urban Data Hubs",
    description: "Real estate investment trusts convert suburban corporate campuses into low-latency edge edge computing facilities and battery backup yards.",
    url: "https://www.forbes.com",
    source: "Forbes Business",
    category: "Business",
    published_at: new Date(Date.now() - 1000 * 60 * 310).toISOString(),
    url_to_image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=800&q=80",
  },
  {
    title: "Global Supply Chain Pressure Index Drops to Lowest Level Since 2019",
    description: "Maritime freight spot rates normalize across trans-Pacific and Asia-Europe shipping lanes while automated container terminals clear port bottlenecks.",
    url: "https://www.bloomberg.com",
    source: "Bloomberg",
    category: "Business",
    published_at: new Date(Date.now() - 1000 * 60 * 350).toISOString(),
    url_to_image: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=800&q=80",
  },
  {
    title: "Fintech Platforms Integrate Real-Time Corporate Cash Management With Automated Yield Sweeps",
    description: "Small and medium enterprises tap treasury yields previously exclusive to Fortune 500 CFOs through algorithmically balanced money market APIs.",
    url: "https://techcrunch.com",
    source: "TechCrunch",
    category: "Business",
    published_at: new Date(Date.now() - 1000 * 60 * 390).toISOString(),
    url_to_image: "https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=800&q=80",
  },
  {
    title: "Global Copper Demand Reaches All-Time High Driven by Grid Modernization & EV Rollouts",
    description: "Commodity strategists forecast multi-year supply deficits as copper smelters operate near maximum rated utilization amid expanding electrification.",
    url: "https://www.reuters.com",
    source: "Reuters Commodities",
    category: "Business",
    published_at: new Date(Date.now() - 1000 * 60 * 430).toISOString(),
    url_to_image: "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=800&q=80",
  },
  {
    title: "Corporate Green Bonds Exceed $1 Trillion in Annual Issuance Under Strict Audit Criteria",
    description: "Asset managers flock to verified green sustainability debt yielding competitive investment-grade spreads backed by renewable energy projects.",
    url: "https://www.wsj.com",
    source: "Wall Street Journal",
    category: "Business",
    published_at: new Date(Date.now() - 1000 * 60 * 480).toISOString(),
    url_to_image: "https://images.unsplash.com/photo-1450133064473-71024230f91b?auto=format&fit=crop&w=800&q=80",
  },
  {
    title: "Automated Tax & Regulatory Compliance Platforms Reduce Audit Filing Cycles From Months to Days",
    description: "Multinational corporations report 80% decrease in cross-jurisdictional reporting discrepancies following deployment of deterministic rule engines.",
    url: "https://www.bloomberg.com",
    source: "Bloomberg Tax",
    category: "Business",
    published_at: new Date(Date.now() - 1000 * 60 * 520).toISOString(),
    url_to_image: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=800&q=80",
  },
  {
    title: "Global Air Travel Bookings Surpass Pre-Pandemic Baselines by 14% With Premium Cabin Upsell",
    description: "International carriers order high-efficiency widebody composite aircraft as corporate executive and luxury leisure travel demand surges.",
    url: "https://www.cnbc.com",
    source: "CNBC Travel",
    category: "Business",
    published_at: new Date(Date.now() - 1000 * 60 * 560).toISOString(),
    url_to_image: "https://images.unsplash.com/photo-1436491865332-7a61a109cc05?auto=format&fit=crop&w=800&q=80",
  },
  {
    title: "Private Credit Funds Close Record $45B Facility to Fund Infrastructure & Enterprise Software",
    description: "Non-bank private lenders offer bespoke structured debt arrangements to middle-market firms seeking non-dilutive balance sheet expansion.",
    url: "https://www.ft.com",
    source: "Financial Times",
    category: "Business",
    published_at: new Date(Date.now() - 1000 * 60 * 610).toISOString(),
    url_to_image: "https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?auto=format&fit=crop&w=800&q=80",
  },
  {
    title: "India Emerges as Third-Largest Global Tech Startup Ecosystem With $28B Annual Inflow",
    description: "Deep-tech, semiconductor design, and SaaS enterprises based in Bengaluru, Hyderabad, and Pune attract marquee international venture syndicates.",
    url: "https://economictimes.indiatimes.com",
    source: "Economic Times",
    category: "Business",
    published_at: new Date(Date.now() - 1000 * 60 * 650).toISOString(),
    url_to_image: "https://images.unsplash.com/photo-1524492412937-b28074a5d7da?auto=format&fit=crop&w=800&q=80",
  },

  // ── SCIENCE (15 articles) ──
  {
    title: "James Webb Space Telescope Identifies Atmospheric Carbon Dioxide and Water on Habitable-Zone Exoplanet",
    description: "Spectroscopic data from exoplanet K2-18b reveals methane, CO2, and absence of ammonia, strongly supporting predictions of an ocean-covered world.",
    url: "https://www.nasa.gov",
    source: "NASA",
    category: "Science",
    published_at: new Date(Date.now() - 1000 * 60 * 40).toISOString(),
    url_to_image: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=800&q=80",
  },
  {
    title: "Fusion Reactor Achieves Net Energy Gain of 3.8 Megajoules in Sustained Plasma Shot",
    description: "National ignition scientists confirm repeated thermodynamic breakeven utilizing high-power ultraviolet lasers and improved diamond capsule targets.",
    url: "https://www.nature.com",
    source: "Nature",
    category: "Science",
    published_at: new Date(Date.now() - 1000 * 60 * 70).toISOString(),
    url_to_image: "https://images.unsplash.com/photo-1507413245164-6160d8298b31?auto=format&fit=crop&w=800&q=80",
  },
  {
    title: "Deep-Sea Expedition Discovers 120 Uncatalogued Bioluminescent Species in Mariana Trench",
    description: "Autonomous submersibles operating at 10,000 meters map unique benthic ecosystems thriving entirely through chemosynthesis around hydrothermal vents.",
    url: "https://www.nationalgeographic.com",
    source: "National Geographic",
    category: "Science",
    published_at: new Date(Date.now() - 1000 * 60 * 115).toISOString(),
    url_to_image: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=800&q=80",
  },
  {
    title: "Paleontologists Unearth Pristine 80-Million-Year-Old Feathered Dinosaur Fossil With Soft Tissue",
    description: "High-resolution synchrotron radiation scans reveal cellular-level preservation of melanosomes, confirming iridescent structural coloration.",
    url: "https://www.sciencemag.org",
    source: "Science Magazine",
    category: "Science",
    published_at: new Date(Date.now() - 1000 * 60 * 150).toISOString(),
    url_to_image: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=800&q=80",
  },
  {
    title: "Gravitational Wave Observatories Detect Coalescence of Rare Intermediate-Mass Black Hole Pair",
    description: "LIGO and Virgo detectors capture spacetime distortions from a binary system merger that produced an astronomical remnant 180 times the mass of the Sun.",
    url: "https://physicsworld.com",
    source: "Physics World",
    category: "Science",
    published_at: new Date(Date.now() - 1000 * 60 * 190).toISOString(),
    url_to_image: "https://images.unsplash.com/photo-1462331940025-496dfbfc7564?auto=format&fit=crop&w=800&q=80",
  },
  {
    title: "Atmospheric Chemists Verify Rapid Recovery of Antarctic Ozone Layer Ahead of 2060 Projections",
    description: "Global compliance with chlorofluorocarbon bans continues to yield measurable reductions in polar stratospheric chlorine concentrations.",
    url: "https://www.scientificamerican.com",
    source: "Scientific American",
    category: "Science",
    published_at: new Date(Date.now() - 1000 * 60 * 230).toISOString(),
    url_to_image: "https://images.unsplash.com/photo-1534088568595-a066f410bcda?auto=format&fit=crop&w=800&q=80",
  },
  {
    title: "Mars Rover Uncovers Organic Carbon Molecules in Ancient Lacustrine Mudstones on Jezero Crater",
    description: "Micro-imaging spectrometer confirms rich carbon chain compounds that were sheltered inside silica-cemented strata for over 3.5 billion years.",
    url: "https://www.space.com",
    source: "Space.com",
    category: "Science",
    published_at: new Date(Date.now() - 1000 * 60 * 270).toISOString(),
    url_to_image: "https://images.unsplash.com/photo-1614728894747-a83421e2b9c9?auto=format&fit=crop&w=800&q=80",
  },
  {
    title: "Neurologists Map the Complete Synaptic Connectome of Complex Mammalian Brain Region",
    description: "Using electron microscope tomography, researchers catalog 50 million synapses across cerebral neocortex tissue with nanometer resolution.",
    url: "https://www.nature.com/neuro",
    source: "Nature Neuroscience",
    category: "Science",
    published_at: new Date(Date.now() - 1000 * 60 * 315).toISOString(),
    url_to_image: "https://images.unsplash.com/photo-1507668077129-56e32842fceb?auto=format&fit=crop&w=800&q=80",
  },
  {
    title: "Geneticists Successfully Synthesize Drought-Resilient C4 Photosynthesis in Rice Crops",
    description: "Bioengineered crop yields 35% more grain while requiring 40% less water in arid test fields, promising massive climate-adaptive food security.",
    url: "https://www.cell.com",
    source: "Cell",
    category: "Science",
    published_at: new Date(Date.now() - 1000 * 60 * 365).toISOString(),
    url_to_image: "https://images.unsplash.com/photo-1500937386664-56d1dfef3854?auto=format&fit=crop&w=800&q=80",
  },
  {
    title: "Laser Interferometers Detect Micro-Seismic Earth Core Oscillations Providing Deep Planetary Map",
    description: "Geophysicists demonstrate that Earth's solid inner core periodically rotates at differential rates relative to the mantle.",
    url: "https://eos.org",
    source: "Eos Earth Science",
    category: "Science",
    published_at: new Date(Date.now() - 1000 * 60 * 415).toISOString(),
    url_to_image: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=800&q=80",
  },
  {
    title: "Cryo-EM Visualizes Molecular Action of Ribosome Inhibitor Against Resistant Superbugs",
    description: "Structural biologists pinpoint atomic-level binding pockets that prevent bacteria from translating protective cell-wall enzymes.",
    url: "https://www.sciencemag.org",
    source: "Science",
    category: "Science",
    published_at: new Date(Date.now() - 1000 * 60 * 470).toISOString(),
    url_to_image: "https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?auto=format&fit=crop&w=800&q=80",
  },
  {
    title: "Archaeologists Use Lidar to Uncover Sprawling Pre-Columbian Megacities in Amazon Basin",
    description: "Airborne laser mapping cuts through dense jungle canopy, revealing interconnected causeways, agricultural terraces, and civic plazas.",
    url: "https://www.nationalgeographic.com",
    source: "National Geographic",
    category: "Science",
    published_at: new Date(Date.now() - 1000 * 60 * 530).toISOString(),
    url_to_image: "https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?auto=format&fit=crop&w=800&q=80",
  },
  {
    title: "Quantum Entanglement Preserved Across 1,200-Kilometer Fiber Network With Optical Repeaters",
    description: "Milestone test validates commercial quantum key distribution (QKD) infrastructure capable of unhackable continental communication.",
    url: "https://physicsworld.com",
    source: "Physics World",
    category: "Science",
    published_at: new Date(Date.now() - 1000 * 60 * 590).toISOString(),
    url_to_image: "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=800&q=80",
  },
  {
    title: "Solar Probe Performs Closest Flyby of Sun at 400,000 MPH, Sampling Coronal Mass Ejection",
    description: "Heat-shielded instruments record fine magnetic reconnection structures that drive solar wind acceleration toward the inner planets.",
    url: "https://www.nasa.gov",
    source: "NASA Science",
    category: "Science",
    published_at: new Date(Date.now() - 1000 * 60 * 640).toISOString(),
    url_to_image: "https://images.unsplash.com/photo-1532693322450-2cb5c511067d?auto=format&fit=crop&w=800&q=80",
  },
  {
    title: "Graphene Aerogel Filter Desalinates Seawater Using Passive Solar Evaporation With 99% Purity",
    description: "Materials engineers design low-cost capillary evaporators that generate drinkable water from high-salinity brine using sunlight alone.",
    url: "https://www.nature.com/naturematerials",
    source: "Nature Materials",
    category: "Science",
    published_at: new Date(Date.now() - 1000 * 60 * 690).toISOString(),
    url_to_image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80",
  },

  // ── HEALTH & MEDICINE (15 articles) ──
  {
    title: "Universal mRNA Vaccine for Seasonal & Avian Influenza Shows 94% Efficacy in Phase 3 Trials",
    description: "Multi-valent formulation targeting conserved viral stalk proteins generates neutralizing antibodies across 20 known influenza hemagglutinin subtypes.",
    url: "https://www.thelancet.com",
    source: "The Lancet",
    category: "Health",
    published_at: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    url_to_image: "https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?auto=format&fit=crop&w=800&q=80",
  },
  {
    title: "FDA Grants Priority Approval for In-Vivo CRISPR Therapy Halting Genetic Cardiomyopathy",
    description: "Lipid nanoparticle delivery system corrects pathogenic genetic mutations directly inside heart tissue, reversing ventricular wall thickening in patients.",
    url: "https://www.nejm.org",
    source: "New England Journal of Medicine",
    category: "Health",
    published_at: new Date(Date.now() - 1000 * 60 * 65).toISOString(),
    url_to_image: "https://images.unsplash.com/photo-1579684385127-1ef15d508118?auto=format&fit=crop&w=800&q=80",
  },
  {
    title: "AI Diagnostic Scan Detects Early-Stage Alzheimer's Biomarkers 8 Years Before Symptom Onset",
    description: "Non-invasive retinal scans combined with neural network pattern analysis detect microvascular amyloid deposits with 97% clinical accuracy.",
    url: "https://www.bbc.com/news/health",
    source: "BBC Health",
    category: "Health",
    published_at: new Date(Date.now() - 1000 * 60 * 105).toISOString(),
    url_to_image: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=800&q=80",
  },
  {
    title: "Next-Generation GLP-1 Multi-Receptor Agonist Demonstrates 28% Sustained Weight Loss in Study",
    description: "Triple-hormone agonist targeting GLP-1, GIP, and glucagon also significantly reduces liver steatosis and improves cardiovascular lipid profiles.",
    url: "https://www.reuters.com/health",
    source: "Reuters Health",
    category: "Health",
    published_at: new Date(Date.now() - 1000 * 60 * 140).toISOString(),
    url_to_image: "https://images.unsplash.com/photo-1505751172876-fa1923c5c528?auto=format&fit=crop&w=800&q=80",
  },
  {
    title: "Implantable Bioartificial Kidney Passes Long-Term Preclinical Safety Trials Without Immunosuppression",
    description: "Silicon nanopore membrane bioreactors containing human renal tubule cells continuously filter blood and regulate electrolyte balance in animal models.",
    url: "https://www.sciencedaily.com",
    source: "ScienceDaily",
    category: "Health",
    published_at: new Date(Date.now() - 1000 * 60 * 185).toISOString(),
    url_to_image: "https://images.unsplash.com/photo-1582719508461-905c673771fd?auto=format&fit=crop&w=800&q=80",
  },
  {
    title: "New Class of Narrow-Spectrum Antibiotics Synthesized to Destroy Drug-Resistant Acinetobacter",
    description: "Compounds disrupt the LptD lipopolysaccharide transport machinery without damaging beneficial gut microbiome bacteria.",
    url: "https://www.nature.com",
    source: "Nature Medicine",
    category: "Health",
    published_at: new Date(Date.now() - 1000 * 60 * 225).toISOString(),
    url_to_image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=800&q=80",
  },
  {
    title: "Non-Invasive Focused Ultrasound Safely Opens Blood-Brain Barrier to Deliver Chemotherapy",
    description: "Clinical oncologists achieve localized targeted drug absorption in glioblastoma brain tumors without surgical craniotomy.",
    url: "https://www.cancer.gov",
    source: "National Cancer Institute",
    category: "Health",
    published_at: new Date(Date.now() - 1000 * 60 * 275).toISOString(),
    url_to_image: "https://images.unsplash.com/photo-1516549655169-df83a0774514?auto=format&fit=crop&w=800&q=80",
  },
  {
    title: "Continuous Optical Glucose Monitoring Ring Clears Clinical Trial With Sub-Milligram Accuracy",
    description: "Non-invasive wearable utilizes Raman spectroscopy to track interstitial glucose flux without needle sticks or consumable sensor patches.",
    url: "https://mobihealthnews.com",
    source: "MobiHealthNews",
    category: "Health",
    published_at: new Date(Date.now() - 1000 * 60 * 330).toISOString(),
    url_to_image: "https://images.unsplash.com/photo-1510519138161-58474ebf8484?auto=format&fit=crop&w=800&q=80",
  },
  {
    title: "Cardiologists Successfully Perform Robotically Assisted Fully Remote Percutaneous Heart Stenting",
    description: "Interventional specialist operates robotic catheters via 5G fiber link from 400 miles away, treating an acute coronary occlusion in 24 minutes.",
    url: "https://www.medscape.com",
    source: "Medscape",
    category: "Health",
    published_at: new Date(Date.now() - 1000 * 60 * 380).toISOString(),
    url_to_image: "https://images.unsplash.com/photo-1551076805-e1869033e561?auto=format&fit=crop&w=800&q=80",
  },
  {
    title: "Cellular Senescence Reversal Demonstrated in Human Skin Tissue Using Yamanaka Factors",
    description: "Transient epigenetic reprogramming restores collagen synthesis and cellular repair pathways without inducing pluripotent oncogenic transformation.",
    url: "https://www.cell.com",
    source: "Aging Cell",
    category: "Health",
    published_at: new Date(Date.now() - 1000 * 60 * 435).toISOString(),
    url_to_image: "https://images.unsplash.com/photo-1512290900672-1f55b9e59d60?auto=format&fit=crop&w=800&q=80",
  },
  {
    title: "Global WHO Initiative Cuts Childhood Malaria Mortality by 62% in Target Regions",
    description: "Widespread deployment of R21/Matrix-M malaria vaccine alongside dual-active ingredient mosquito netting dramatically curbs transmission.",
    url: "https://www.who.int",
    source: "World Health Organization",
    category: "Health",
    published_at: new Date(Date.now() - 1000 * 60 * 490).toISOString(),
    url_to_image: "https://images.unsplash.com/photo-1532938911079-1b06ac7ceec7?auto=format&fit=crop&w=800&q=80",
  },
  {
    title: "Brain-Computer Interface Restores Natural Conversational Speech to Paralyzed Patient at 90 WPM",
    description: "Subdural microelectrode arrays decode neural motor intentions into synthesized natural voice inflections with negligible conversational latency.",
    url: "https://www.nature.com",
    source: "Nature",
    category: "Health",
    published_at: new Date(Date.now() - 1000 * 60 * 545).toISOString(),
    url_to_image: "https://images.unsplash.com/photo-1507668077129-56e32842fceb?auto=format&fit=crop&w=800&q=80",
  },
  {
    title: "Personalized Neoantigen Cancer Vaccine Shrinks Recurrent Pancreatic Tumors in 82% of Patients",
    description: "Tailored mRNA vaccines manufactured within three weeks of surgical tumor biopsy train cytotoxic T-cells against specific patient neoepitopes.",
    url: "https://www.bloomberg.com",
    source: "Bloomberg Health",
    category: "Health",
    published_at: new Date(Date.now() - 1000 * 60 * 600).toISOString(),
    url_to_image: "https://images.unsplash.com/photo-1579684385127-1ef15d508118?auto=format&fit=crop&w=800&q=80",
  },
  {
    title: "Regenerative Stem Cell Hydrogel Restores Full Meniscal Cartilage Function in Knee Joints",
    description: "Injectable biopolymer scaffold promotes natural chondrocyte migration, eliminating the need for joint replacement surgery in pilot cohorts.",
    url: "https://www.sciencemag.org",
    source: "Science Translational Medicine",
    category: "Health",
    published_at: new Date(Date.now() - 1000 * 60 * 655).toISOString(),
    url_to_image: "https://images.unsplash.com/photo-1530497610245-94d3c16cda28?auto=format&fit=crop&w=800&q=80",
  },
  {
    title: "Sleep Quality Tracking Algorithms Discover Critical Glymphatic Toxin Clearance Windows",
    description: "Sleep neuroscientists determine that slow-wave delta cycles facilitate optimal cerebrospinal fluid flushing of metabolic tau protein debris.",
    url: "https://www.nih.gov",
    source: "National Institutes of Health",
    category: "Health",
    published_at: new Date(Date.now() - 1000 * 60 * 710).toISOString(),
    url_to_image: "https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?auto=format&fit=crop&w=800&q=80",
  },

  // ── SPORTS (16 articles) ──
  {
    title: "Champions League Quarterfinals Set After Dramatic Penalty Shootout Decider",
    description: "Defending champions advance in sensational European tie, setting up an electric semifinal clash between contrasting tactical styles.",
    url: "https://www.bbc.com/sport",
    source: "BBC Sport",
    category: "Sports",
    published_at: new Date(Date.now() - 1000 * 60 * 20).toISOString(),
    url_to_image: "https://images.unsplash.com/photo-1508098682722-e99c43a406b2?auto=format&fit=crop&w=800&q=80",
  },
  {
    title: "Formula 1 Unveils 2026 Engine Regulations With 100% Sustainable Fuel & Boosted Electrical Output",
    description: "F1 constructors begin track dyno testing on new hybrid power units delivering 350kW electric boost and active aerodynamic downforce control.",
    url: "https://www.motorsport.com",
    source: "Motorsport.com",
    category: "Sports",
    published_at: new Date(Date.now() - 1000 * 60 * 50).toISOString(),
    url_to_image: "https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=800&q=80",
  },
  {
    title: "Olympic Committee Confirms Cricket, Flag Football, and Squash for 2028 Los Angeles Games",
    description: "International Olympic officials formalize the program additions, expanding global television viewership and youth participation initiatives.",
    url: "https://www.espn.com",
    source: "ESPN",
    category: "Sports",
    published_at: new Date(Date.now() - 1000 * 60 * 85).toISOString(),
    url_to_image: "https://images.unsplash.com/photo-1461896836934-ffe607ba8211?auto=format&fit=crop&w=800&q=80",
  },
  {
    title: "NBA Finals Ratings Surge 24% Driven by High-Scoring Dynamic Offenses and Global Stars",
    description: "Digital streaming viewership breaks historical streaming records as international basketball talent takes center stage in championship series.",
    url: "https://www.theathletic.com",
    source: "The Athletic",
    category: "Sports",
    published_at: new Date(Date.now() - 1000 * 60 * 125).toISOString(),
    url_to_image: "https://images.unsplash.com/photo-1546519638-68e109498ffc?auto=format&fit=crop&w=800&q=80",
  },
  {
    title: "Grand Slam Tennis Final Thriller Goes to Five Sets in Record 4-Hour 45-Minute Epic",
    description: "World number one rallies from two sets down to capture the title with sensational baseline winners and relentless physical stamina.",
    url: "https://www.reuters.com/sports",
    source: "Reuters Sports",
    category: "Sports",
    published_at: new Date(Date.now() - 1000 * 60 * 170).toISOString(),
    url_to_image: "https://images.unsplash.com/photo-1595435934249-5df7ed86e1c0?auto=format&fit=crop&w=800&q=80",
  },
  {
    title: "Marathon World Record Shattered by 38 Seconds With Precision Pacing & Carbon Footwear",
    description: "Elite runner clocks sub-2:00:30 official marathon pace through cool morning conditions in Berlin, rewriting distance running physiology.",
    url: "https://www.runnersworld.com",
    source: "Runner's World",
    category: "Sports",
    published_at: new Date(Date.now() - 1000 * 60 * 215).toISOString(),
    url_to_image: "https://images.unsplash.com/photo-1452626038306-9aae5e071dd3?auto=format&fit=crop&w=800&q=80",
  },
  {
    title: "Premier League Agrees Historic $8.5 Billion Domestic Television Broadcast Package",
    description: "Broadcasters commit to multi-year live transmission rights with enhanced ultra-HD 360-degree interactive camera feeds for global viewers.",
    url: "https://www.skysports.com",
    source: "Sky Sports",
    category: "Sports",
    published_at: new Date(Date.now() - 1000 * 60 * 265).toISOString(),
    url_to_image: "https://images.unsplash.com/photo-1522778119026-d647f0596c20?auto=format&fit=crop&w=800&q=80",
  },
  {
    title: "PGA Tour and DP World Tour Finalize Historic Strategic Enterprise Investment Structure",
    description: "Global professional golf ecosystem unifies tournament calendars and commercial sponsorships, expanding prize purses to $600M annually.",
    url: "https://www.golfdigest.com",
    source: "Golf Digest",
    category: "Sports",
    published_at: new Date(Date.now() - 1000 * 60 * 310).toISOString(),
    url_to_image: "https://images.unsplash.com/photo-1535131749006-b7f58c99034b?auto=format&fit=crop&w=800&q=80",
  },
  {
    title: "FIFA World Cup 2026 Ticket Registration Exceeds 15 Million Within First 72 Hours",
    description: "Tournament across United States, Canada, and Mexico anticipates record stadium attendance and historic economic tourism impact.",
    url: "https://www.fifa.com",
    source: "FIFA Official",
    category: "Sports",
    published_at: new Date(Date.now() - 1000 * 60 * 360).toISOString(),
    url_to_image: "https://images.unsplash.com/photo-1518091043644-c1d4457512c6?auto=format&fit=crop&w=800&q=80",
  },
  {
    title: "Cricket World Cup Final Attracts Record Peak 65 Million Concurrent Streaming Viewers",
    description: "Electrifying run-chase in front of 110,000 capacity stadium crowd caps thrilling tournament showcasing world-class spin and pace bowling.",
    url: "https://www.espncricinfo.com",
    source: "ESPN Cricinfo",
    category: "Sports",
    published_at: new Date(Date.now() - 1000 * 60 * 410).toISOString(),
    url_to_image: "https://images.unsplash.com/photo-1531415074868-036b1c5f53ec?auto=format&fit=crop&w=800&q=80",
  },
  {
    title: "Tour de France Mountain Stage Decided by Stunning Solo Breakaway on Legendary Col du Tourmalet",
    description: "Yellow jersey contender launches devastating acceleration 40km from the summit finish, gaining critical minutes in overall classification.",
    url: "https://www.cyclingnews.com",
    source: "Cycling News",
    category: "Sports",
    published_at: new Date(Date.now() - 1000 * 60 * 465).toISOString(),
    url_to_image: "https://images.unsplash.com/photo-1517649763962-0c623266ddc0?auto=format&fit=crop&w=800&q=80",
  },
  {
    title: "Women's Super League Attendance Grows by 68% in Record-Breaking Season",
    description: "Major stadium venues sell out across London and Manchester as professional women's football establishes prime-time broadcast dominance.",
    url: "https://www.theguardian.com/football",
    source: "The Guardian Sport",
    category: "Sports",
    published_at: new Date(Date.now() - 1000 * 60 * 520).toISOString(),
    url_to_image: "https://images.unsplash.com/photo-1517466787929-bc90951d0974?auto=format&fit=crop&w=800&q=80",
  },
  {
    title: "Super Bowl Halftime Show and Commercial Ads Set New Commercial Value Benchmarks",
    description: "30-second advertising spots surpass $7.5M as advertisers deploy interactive augmented-reality tie-ins for over 125 million broadcast viewers.",
    url: "https://www.variety.com",
    source: "Variety Sports & Media",
    category: "Sports",
    published_at: new Date(Date.now() - 1000 * 60 * 575).toISOString(),
    url_to_image: "https://images.unsplash.com/photo-1566577739112-5180d4bf9390?auto=format&fit=crop&w=800&q=80",
  },
  {
    title: "Extreme Sailing Foiling Catamarans Reach Unprecedented 58 Knots in Open Water Regatta",
    description: "Sailors harness autonomous wing-sail trim systems to glide above wave crests at triple the speed of the ambient true wind.",
    url: "https://www.yachtingworld.com",
    source: "Yachting World",
    category: "Sports",
    published_at: new Date(Date.now() - 1000 * 60 * 630).toISOString(),
    url_to_image: "https://images.unsplash.com/photo-1500917293891-ef795e70e1f6?auto=format&fit=crop&w=800&q=80",
  },
  {
    title: "MLB Pitch Tracking Biometrics Drastically Reduce UCL Strain Among Fastball Starters",
    description: "Computer vision motion capture wearable sensors help pitching coaches optimize forearm arm-slot mechanics and manage pitch counts safely.",
    url: "https://www.baseballprospectus.com",
    source: "Baseball Prospectus",
    category: "Sports",
    published_at: new Date(Date.now() - 1000 * 60 * 680).toISOString(),
    url_to_image: "https://images.unsplash.com/photo-1508344928928-7165b67de128?auto=format&fit=crop&w=800&q=80",
  },
  {
    title: "World Athletics Introduces Smart Track Sensors Providing Instantaneous Reaction Time Analysis",
    description: "High-density piezo pressure sensors in starting blocks eliminate false-start measurement ambiguities at international sprint championships.",
    url: "https://worldathletics.org",
    source: "World Athletics",
    category: "Sports",
    published_at: new Date(Date.now() - 1000 * 60 * 730).toISOString(),
    url_to_image: "https://images.unsplash.com/photo-1530549387789-4c1017266635?auto=format&fit=crop&w=800&q=80",
  },

  // ── ENTERTAINMENT & MEDIA (18 articles) ──
  {
    title: "Academy Awards Honor Groundbreaking Sci-Fi Masterpiece With 7 Major Statuettes",
    description: "Visually arresting cinematic epic sweeps Best Picture, Director, and Cinematography following universal acclaim from critics and moviegoers.",
    url: "https://www.hollywoodreporter.com",
    source: "Hollywood Reporter",
    category: "Entertainment",
    published_at: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
    url_to_image: "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=800&q=80",
  },
  {
    title: "Streaming Titans Consolidate Platform Libraries to Create Comprehensive Unified Service",
    description: "Major entertainment studios finalize joint subscriber bundling, reducing churn while offering combined catalogs of prestige television and live sports.",
    url: "https://www.variety.com",
    source: "Variety",
    category: "Entertainment",
    published_at: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    url_to_image: "https://images.unsplash.com/photo-1574375927938-d5a98e8ffe85?auto=format&fit=crop&w=800&q=80",
  },
  {
    title: "Interactive Generative Video Game Engine Generates Fully Voiced Living Worlds in Real Time",
    description: "Next-generation Unreal Engine title features thousands of non-player characters with persistent memories and dynamic procedural storytelling.",
    url: "https://www.ign.com",
    source: "IGN",
    category: "Entertainment",
    published_at: new Date(Date.now() - 1000 * 60 * 75).toISOString(),
    url_to_image: "https://images.unsplash.com/photo-1538481199705-c710c4e965fc?auto=format&fit=crop&w=800&q=80",
  },
  {
    title: "Global Music Festival Tour Sells Out 2.5 Million Tickets in Under 40 Minutes",
    description: "Multi-genre festival tour across five continents announces immersive spatial audio stages and synchronized holographic artist performances.",
    url: "https://www.billboard.com",
    source: "Billboard",
    category: "Entertainment",
    published_at: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    url_to_image: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&w=800&q=80",
  },
  {
    title: "Independent Animated Feature Film Wins Prestigious Palme d'Or at Cannes Film Festival",
    description: "Hand-painted watercolor aesthetic combined with cutting-edge 3D depth rendering earns 12-minute standing ovation at festival premiere.",
    url: "https://deadline.com",
    source: "Deadline",
    category: "Entertainment",
    published_at: new Date(Date.now() - 1000 * 60 * 160).toISOString(),
    url_to_image: "https://images.unsplash.com/photo-1536440136628-849c177e76a1?auto=format&fit=crop&w=800&q=80",
  },
  {
    title: "Spatial Audio Mixes of Classic Albums Uncover Lost Master Tapes and Vocal Harmonizations",
    description: "Grammy-winning audio engineers restore legendary studio master recordings into pristine 360-degree Dolby Atmos multichannel editions.",
    url: "https://pitchfork.com",
    source: "Pitchfork",
    category: "Entertainment",
    published_at: new Date(Date.now() - 1000 * 60 * 205).toISOString(),
    url_to_image: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=800&q=80",
  },
  {
    title: "Broadway Box Office Reaches Historical Season High Driven by Fresh Original Musicals",
    description: "Theatrical productions see strong influx of domestic and international theatergoers, with sold-out runs extending through holiday schedules.",
    url: "https://www.playbill.com",
    source: "Playbill",
    category: "Entertainment",
    published_at: new Date(Date.now() - 1000 * 60 * 255).toISOString(),
    url_to_image: "https://images.unsplash.com/photo-1507676184212-d03ab07a01bf?auto=format&fit=crop&w=800&q=80",
  },
  {
    title: "Virtual Production LED Volume Stages Replace 70% of Location Green Screens in Hollywood",
    description: "Filmmakers shoot complex extraterrestrial and historical backdrops with real-time camera tracking and in-camera photorealistic lighting.",
    url: "https://www.thewrap.com",
    source: "TheWrap",
    category: "Entertainment",
    published_at: new Date(Date.now() - 1000 * 60 * 300).toISOString(),
    url_to_image: "https://images.unsplash.com/photo-1478760329108-5c3ed9d495a0?auto=format&fit=crop&w=800&q=80",
  },
  {
    title: "Global Manga and Graphic Novel Publishing Surpasses $18 Billion Valuation",
    description: "Simultaneous international digital serialization and luxury hardcover omnibus editions drive record readership across North America and Europe.",
    url: "https://www.animenewsnetwork.com",
    source: "Anime News Network",
    category: "Entertainment",
    published_at: new Date(Date.now() - 1000 * 60 * 345).toISOString(),
    url_to_image: "https://images.unsplash.com/photo-1578632767115-351597cf2477?auto=format&fit=crop&w=800&q=80",
  },
  {
    title: "Electronic Music Artists Pioneer Generative Live Synth Performances Responding to Crowd Energy",
    description: "Audience biometric telemetry and acoustic feedback loop into modular analog synthesizers, creating unrepeatable concert improvisations.",
    url: "https://djmag.com",
    source: "DJ Mag",
    category: "Entertainment",
    published_at: new Date(Date.now() - 1000 * 60 * 395).toISOString(),
    url_to_image: "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=800&q=80",
  },
  {
    title: "Museum of Modern Art Opens Landmark Exhibition on Algorithmic and Digital Artistry",
    description: "Curators assemble four decades of creative computation, kinetic installations, and autonomous code-generated architectural sculptures.",
    url: "https://www.artnews.com",
    source: "ARTnews",
    category: "Entertainment",
    published_at: new Date(Date.now() - 1000 * 60 * 450).toISOString(),
    url_to_image: "https://images.unsplash.com/photo-1547826039-bfc35e0f1ea8?auto=format&fit=crop&w=800&q=80",
  },
  {
    title: "High-Fantasy Book Series Adaptation Garners 80 Million Households in First Ten Days",
    description: "Epic world-building and grounded character performances propel streaming adaptation into the top five most-watched debuts of all time.",
    url: "https://www.indiewire.com",
    source: "IndieWire",
    category: "Entertainment",
    published_at: new Date(Date.now() - 1000 * 60 * 505).toISOString(),
    url_to_image: "https://images.unsplash.com/photo-1463320726281-696a485928c7?auto=format&fit=crop&w=800&q=80",
  },
  {
    title: "Podcasting Networks Expand Video Broadcast Studios With 4K Multi-Camera Production",
    description: "Long-form conversational video journalism dominates YouTube and Spotify charts with millions of dedicated global listeners.",
    url: "https://www.rollingstone.com",
    source: "Rolling Stone",
    category: "Entertainment",
    published_at: new Date(Date.now() - 1000 * 60 * 560).toISOString(),
    url_to_image: "https://images.unsplash.com/photo-1590602847861-f357a9332bbc?auto=format&fit=crop&w=800&q=80",
  },
  {
    title: "Historical Epic Video Game Sets New Standard for Atmospheric Orchestral Scoring",
    description: "Full 90-piece philharmonic orchestra recorded in Prague weaves indigenous folk instruments into an emotional, dynamic combat score.",
    url: "https://www.gamespot.com",
    source: "GameSpot",
    category: "Entertainment",
    published_at: new Date(Date.now() - 1000 * 60 * 615).toISOString(),
    url_to_image: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=800&q=80",
  },
  {
    title: "International Documentary Festival Awards Grand Jury Prize to Ocean Conservation Expose",
    description: "Intrepid investigative filmmakers uncover illicit deep-sea trawling fleets and celebrate indigenous marine sanctuary stewards.",
    url: "https://www.screendaily.com",
    source: "Screen Daily",
    category: "Entertainment",
    published_at: new Date(Date.now() - 1000 * 60 * 670).toISOString(),
    url_to_image: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=800&q=80",
  },
  {
    title: "Vinyl Record Sales Outpace Digital Downloads for Fifth Consecutive Year Among Gen-Z Audiences",
    description: "Music fans champion tangible collectible album packaging, color-splatter pressings, and gatefold lyric booklets.",
    url: "https://www.billboard.com",
    source: "Billboard",
    category: "Entertainment",
    published_at: new Date(Date.now() - 1000 * 60 * 720).toISOString(),
    url_to_image: "https://images.unsplash.com/photo-1539185441755-769473a23570?auto=format&fit=crop&w=800&q=80",
  },
  {
    title: "Immersive VR Opera Production Stuns Audiences With Floating 3D Vocal Harmonies",
    description: "Audiences wear lightweight spatial headsets to walk through surreal, evolving sets while live operatic soloists sing around them.",
    url: "https://www.thestage.co.uk",
    source: "The Stage",
    category: "Entertainment",
    published_at: new Date(Date.now() - 1000 * 60 * 760).toISOString(),
    url_to_image: "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?auto=format&fit=crop&w=800&q=80",
  },
  {
    title: "Global Film Archive Restores 100 Lost Silent Classics in 4K HDR Using Machine Learning",
    description: "Preservationists remove chemical degradation, water damage, and scratches from nitrate negative reels dating back to 1910.",
    url: "https://www.bfi.org.uk",
    source: "British Film Institute",
    category: "Entertainment",
    published_at: new Date(Date.now() - 1000 * 60 * 800).toISOString(),
    url_to_image: "https://images.unsplash.com/photo-1485846234645-a62644f84728?auto=format&fit=crop&w=800&q=80",
  },
];

export async function GET(req: Request) {
  const url = new URL(req.url);
  const page = parseInt(url.searchParams.get("page") || "1", 10);
  const limit = parseInt(url.searchParams.get("limit") || "100", 10);
  const category = (url.searchParams.get("category") || "").toLowerCase().trim();
  const topic = (url.searchParams.get("topic") || "").toLowerCase().trim();

  let filtered = HUNDRED_NEWS;

  // Filter by category if specified
  if (category && category !== "all") {
    filtered = HUNDRED_NEWS.filter(
      (n) => n.category.toLowerCase() === category || (category === "business" && n.category.toLowerCase() === "finance"),
    );
    if (filtered.length === 0) filtered = HUNDRED_NEWS;
  }

  // Filter by search topic/query if provided
  if (topic) {
    const topicFiltered = filtered.filter(
      (n) =>
        n.title.toLowerCase().includes(topic) ||
        n.description.toLowerCase().includes(topic) ||
        n.source.toLowerCase().includes(topic),
    );
    if (topicFiltered.length > 0) {
      filtered = topicFiltered;
    }
  }

  // Pagination support
  const startIndex = (page - 1) * limit;
  const paginated = filtered.slice(startIndex, startIndex + limit);

  const articles = paginated.map((a) => ({
    ...a,
    publishedAt: a.published_at,
    urlToImage: a.url_to_image,
  }));

  return NextResponse.json({
    articles,
    news: articles,
    page,
    limit,
    has_more: startIndex + limit < filtered.length,
    hasMore: startIndex + limit < filtered.length,
    total_results: filtered.length,
    total: filtered.length,
  });
}
